export const paths = {
  home: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  projects: "/projects",
  projectCreate: "/projects/create",
  projectDetails: (projectId: string | number) => `/projects/${projectId}`,
  submissions: "/submissions",
  submissionCreate: "/submissions/create",
  documents: "/documents",
  documentDetails: (documentId: string | number) => `/documents/${documentId}`,
  evaluations: "/evaluations",
  evaluationDetails: (evaluationId: string | number) => `/evaluations/${evaluationId}`,
  repositoryAnalysis: "/repository-analysis",
  deploymentValidation: "/deployment-validation",
  reports: "/reports",
  settings: "/settings",
  courseClasses: "/course-classes",
  courseClassCreate: "/course-classes/create",
  courseClassEdit: (courseClassId: string | number) => `/course-classes/${courseClassId}/edit`,
  myCourseClasses: "/my-course-classes",
  proposals: "/proposals",
  proposalCreate: "/proposals/create",
  proposalDetails: (proposalId: string | number) => `/proposals/${proposalId}`,
  proposalEdit: (proposalId: string | number) => `/proposals/${proposalId}/edit`,
};
